services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frostel_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frostel_network
    volumes:
      - .:/app # For development hot reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/api/health/"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s

  mysql:
    image: mysql:8.0
    container_name: frostel_mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${FROSTEL_MYSQL_DATABASE}
      MYSQL_USER: ${FROSTEL_MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${FROSTEL_MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${FROSTEL_MYSQL_PASSWORD}
    ports:
      - "3333:3306"
    networks:
      - frostel_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${FROSTEL_MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s # Gives the DB some time to start

volumes:
  mysql_data:

networks:
  frostel_network:
    driver: bridge
